name: CI Pipeline

# Cette action de workflow est déclenchée lors des push et des pull requests.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code du dépôt

      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configurer l'environnement Node.js (utiliser une version spécifique de Node.js)

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Installer les dépendances

      - name: Install dependencies
        run: npm install

      # Step 4: Exécuter les tests
      - name: Run tests
        run: npm test
